query BlockQuery ($block_id: ID!) {
  block(id: $block_id) {
    created_at
    description
    editable
    id
    initial_input_data
    name
    schema
    source

    author {
      handle
    }

    environment {
      id
    }

    subscription {
      active
      data_overrides
      id
      trigger_options

      trigger {
        id
        name
        description
        options_schema
        data_schema

        service {
          name
          domain
        }
      }
    }
  }

  session {
    api_key
  }

  environments {
    id
    name
  }
}
