#import "./fragments/subscription.gql"

query BlockQuery ($block_id: ID!) {
  block(id: $block_id) {
    created_at
    description
    editable
    id
    initial_input_data
    name
    schema
    source

    author {
      handle
    }

    environment {
      id
    }

    subscription {
      ...subscription
    }
  }

  session {
    api_key
  }

  environments {
    id
    name
  }
}
