#import "graphql/fragments/subscription.gql"

query BlockQuery ($block_id: ID!) {
  block(id: $block_id) {
    created_at
    description
    editable
    id
    name
    source

    author {
      handle
    }

    subscription {
      ...subscription
    }
  }

  credentialed_services {
    id
    name
    domain
  }
}
